

from turtle import *
import turtle as KREGGSCODE
t =KREGGSCODE.Turtle()
KREGGSCODE.title("kreggscode ganapathi")
KREGGSCODE.speed(6)

KREGGSCODE.bgcolor("brown")
KREGGSCODE.color("yellow")
KREGGSCODE.pensize(5)

KREGGSCODE.left(60)    
KREGGSCODE.fd(50)
KREGGSCODE.left(15)
KREGGSCODE.circle(100,90)
KREGGSCODE.fd(30)
KREGGSCODE.pensize(10)
KREGGSCODE.penup()
KREGGSCODE.right(90)
KREGGSCODE.fd(20)
KREGGSCODE.pendown()

KREGGSCODE.right(40)
KREGGSCODE.circle(-50,90)
KREGGSCODE.fd(20)
KREGGSCODE.left(150)


KREGGSCODE.color("yellow")
KREGGSCODE.penup()
KREGGSCODE.fd(40)
KREGGSCODE.left(20)
KREGGSCODE.pendown()
KREGGSCODE.circle(50,90)



KREGGSCODE.color("yellow")
KREGGSCODE.penup()
goto(0,0)
KREGGSCODE.pensize(5)
KREGGSCODE.pendown()
KREGGSCODE.left(30)
KREGGSCODE.fd(120)
KREGGSCODE.circle(60,270)

#eye
KREGGSCODE.color("white")
KREGGSCODE.penup()
KREGGSCODE.forward(30)
KREGGSCODE.right(50)
KREGGSCODE.forward(135)
KREGGSCODE.pendown()
KREGGSCODE.pensize(8)
KREGGSCODE.circle(50,90)
KREGGSCODE.left(95)
KREGGSCODE.penup
KREGGSCODE.circle(60,75)

#eyebrows

KREGGSCODE.penup()
KREGGSCODE.forward(15)
KREGGSCODE.left(90)
KREGGSCODE.pensize(2)
KREGGSCODE.pendown()
KREGGSCODE.circle(70,90)

#ear
KREGGSCODE.pensize(5)
KREGGSCODE.penup()
KREGGSCODE.forward(75)
KREGGSCODE.right(90)
KREGGSCODE.forward(20)
KREGGSCODE.pendown()
KREGGSCODE.circle(90,90)
KREGGSCODE.forward(20)

KREGGSCODE.circle(30,170)
KREGGSCODE.right(180)
KREGGSCODE.circle(28,180)
KREGGSCODE.right(160)
KREGGSCODE.circle(25,180)
KREGGSCODE.right(160)
KREGGSCODE.circle(22,160)
KREGGSCODE.forward(20)
KREGGSCODE.circle(60,45)

# trunk

KREGGSCODE.penup()
goto(0,0)
KREGGSCODE.left(130)
KREGGSCODE.fd(140)
KREGGSCODE.right(250)
KREGGSCODE.backward(20)
KREGGSCODE.circle(80,20)
KREGGSCODE.circle(20,40)

KREGGSCODE.right(110)
KREGGSCODE.penup()
KREGGSCODE.fd(20)
KREGGSCODE.pendown()
KREGGSCODE.pensize(10)
KREGGSCODE.forward(50)
KREGGSCODE.circle(100,80)
KREGGSCODE.pensize(9)
KREGGSCODE.circle(150,50)
KREGGSCODE.pensize(7)
KREGGSCODE.circle(100,60)
KREGGSCODE.pensize(5)
KREGGSCODE.circle(90,60)
KREGGSCODE.pensize(4)
KREGGSCODE.circle(40,60)
KREGGSCODE.circle(10,90)


#head

KREGGSCODE.color("yellow")
KREGGSCODE.penup()

goto(0,0)
goto(-90,290)
KREGGSCODE.right(230)
KREGGSCODE.pendown()

KREGGSCODE.circle(-100,50)
KREGGSCODE.circle(200,20)
KREGGSCODE.circle(50,30)

KREGGSCODE.right(180)

KREGGSCODE.circle(50,30)
KREGGSCODE.circle(200,20)
KREGGSCODE.circle(-100,40)
KREGGSCODE.right(95)
KREGGSCODE.penup()
KREGGSCODE.fd(40)
KREGGSCODE.right(90)
KREGGSCODE.pendown()
KREGGSCODE.circle(100,40)
KREGGSCODE.penup()
KREGGSCODE.circle(35,120)
KREGGSCODE.right(30)
KREGGSCODE.pendown()
KREGGSCODE.pensize(4)
KREGGSCODE.circle(60,50)

###############

KREGGSCODE.penup()
goto(-55,90)
KREGGSCODE.fillcolor("yellow")
KREGGSCODE.begin_fill()
KREGGSCODE.circle(20,180)
KREGGSCODE.end_fill()

KREGGSCODE.penup()
KREGGSCODE.left(75)
KREGGSCODE.fillcolor("yellow")
KREGGSCODE.begin_fill()
KREGGSCODE.circle(70,35)
KREGGSCODE.end_fill()


KREGGSCODE.left(180)
KREGGSCODE.backward(10)
KREGGSCODE.pendown()
KREGGSCODE.left(6)
KREGGSCODE.pensize(5)
KREGGSCODE.color("yellow")
KREGGSCODE.circle(-80,40)
KREGGSCODE.penup()



KREGGSCODE.color("cyan")
goto(-240,420)
KREGGSCODE.right(90)
KREGGSCODE.pendown()
KREGGSCODE.fillcolor("cyan")
KREGGSCODE.begin_fill()
KREGGSCODE.forward(275)
KREGGSCODE.right(130)
KREGGSCODE.forward(100)
KREGGSCODE.end_fill()

KREGGSCODE.penup()
goto(0,420)
KREGGSCODE.right(90)

KREGGSCODE.color("cyan")
KREGGSCODE.fillcolor("cyan")
KREGGSCODE.begin_fill()
KREGGSCODE.fd(100)
KREGGSCODE.right(50)
KREGGSCODE.pendown()
KREGGSCODE.fd(510)
KREGGSCODE.left(90)
KREGGSCODE.right(165)
KREGGSCODE.end_fill()
KREGGSCODE.color("cyan")
KREGGSCODE.fillcolor("cyan")
KREGGSCODE.begin_fill()
KREGGSCODE.fd(540)
KREGGSCODE.right(70)
KREGGSCODE.fd(20)
KREGGSCODE.end_fill()
KREGGSCODE.color("cyan")
KREGGSCODE.fillcolor("cyan")
KREGGSCODE.begin_fill()
KREGGSCODE.fd(540)
KREGGSCODE.right(90)
KREGGSCODE.fd(20)
KREGGSCODE.end_fill()


KREGGSCODE.left(30)
KREGGSCODE.color("cyan")
KREGGSCODE.fillcolor("")
KREGGSCODE.begin_fill()
KREGGSCODE.fd(205)
KREGGSCODE.right(90)
KREGGSCODE.fd(20)
KREGGSCODE.end_fill()


KREGGSCODE.color("yellow")
KREGGSCODE.penup()
goto(0,0)
KREGGSCODE.left(118)
KREGGSCODE.fd(240)
KREGGSCODE.right(30)
KREGGSCODE.pendown()
KREGGSCODE.circle(90,65)
KREGGSCODE.penup()

KREGGSCODE.penup()
goto(-165,70)
KREGGSCODE.left(100)
KREGGSCODE.fd(140)
KREGGSCODE.right(250)
KREGGSCODE.backward(20)
KREGGSCODE.circle(80,20)
KREGGSCODE.circle(20,40)

KREGGSCODE.right(110)
KREGGSCODE.penup()
KREGGSCODE.fd(20)
KREGGSCODE.pendown()
KREGGSCODE.pensize(10)
KREGGSCODE.forward(50)
KREGGSCODE.circle(60,40)
KREGGSCODE.backward(60)



 

KREGGSCODE.speed(0) 



KREGGSCODE.exitonclick()
KREGGSCODE.mainloop()
# KREGGSCODE.done()