


import turtle as shiv
kreggscode_screen = shiv.Screen()
kreggscode_screen.bgcolor('blue')
def kreggscode2(value):
    for i in range(value):
        shiv.right(1)
        shiv.forward(1)
shiv.penup()
shiv.setposition(0, 43)
shiv.pendown()
shiv.begin_fill()
shiv.pencolor('black')
shiv.fillcolor('red')
shiv.pensize(3)
shiv.forward(81.5)
shiv.right(49.4)
shiv.forward(58)
shiv.right(81.42)
shiv.forward(182)
shiv.right(98.36)
shiv.forward(182)
shiv.right(81.42)
shiv.forward(58)
shiv.right(49.4)
shiv.forward(81.5)
shiv.end_fill()
shiv.penup()

shiv.setposition(38, 32)
shiv.pendown()
shiv.begin_fill()
shiv.fillcolor('gold')
shiv.forward(13)
shiv.right(120)
shiv.forward(13)
shiv.right(120)
shiv.forward(13)
shiv.end_fill()
shiv.penup()

shiv.setposition(81.5, 25)
shiv.pendown()
shiv.begin_fill()
shiv.right(210)
shiv.forward(25)
shiv.right(90)
shiv.forward(38)
shiv.right(45)
shiv.circle(82, 90)
shiv.left(90)
shiv.circle(82, 60)
kreggscode2(61)
shiv.left(90)
shiv.forward(57)
shiv.left(90)
shiv.forward(32)
shiv.end_fill()
shiv.penup()
shiv.home()

shiv.setposition(-69, -38)
shiv.pendown()
shiv.begin_fill()
kreggscode2(20)
shiv.forward(33)
shiv.left(10)
shiv.circle(82, 20)
kreggscode2(30)
shiv.forward(10)
shiv.right(110)
kreggscode2(40)
shiv.right(10)
shiv.circle(50, 10)
kreggscode2(45)
shiv.right(5)
shiv.forward(45)
shiv.end_fill()
shiv.penup()
shiv.home()

shiv.setposition(20, -100)
shiv.pendown()
shiv.begin_fill()
shiv.right(135)
shiv.forward(27)
shiv.right(90)
shiv.forward(27)
shiv.right(135)
shiv.forward(38.18)
shiv.end_fill()
shiv.penup()
shiv.home()

shiv.setposition(-57, 32)
shiv.pendown()
shiv.begin_fill()
shiv.right(180)
shiv.forward(18)
shiv.left(45)
shiv.forward(44)
shiv.left(80)
shiv.forward(15)
shiv.left(130)
kreggscode2(40)
shiv.forward(20)
shiv.end_fill()

shiv.hideturtle()
shiv.exitonclick()
